
package br.com.ae.cliente;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CalculadoraDeParcelaService", targetNamespace = "http://webservices.ae.com.br/", wsdlLocation = "http://localhost:10000/calculadoraDeParcela?wsdl")
public class CalculadoraDeParcelaService
    extends Service
{

    private final static URL CALCULADORADEPARCELASERVICE_WSDL_LOCATION;
    private final static WebServiceException CALCULADORADEPARCELASERVICE_EXCEPTION;
    private final static QName CALCULADORADEPARCELASERVICE_QNAME = new QName("http://webservices.ae.com.br/", "CalculadoraDeParcelaService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:10000/calculadoraDeParcela?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CALCULADORADEPARCELASERVICE_WSDL_LOCATION = url;
        CALCULADORADEPARCELASERVICE_EXCEPTION = e;
    }

    public CalculadoraDeParcelaService() {
        super(__getWsdlLocation(), CALCULADORADEPARCELASERVICE_QNAME);
    }

    public CalculadoraDeParcelaService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CALCULADORADEPARCELASERVICE_QNAME, features);
    }

    public CalculadoraDeParcelaService(URL wsdlLocation) {
        super(wsdlLocation, CALCULADORADEPARCELASERVICE_QNAME);
    }

    public CalculadoraDeParcelaService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CALCULADORADEPARCELASERVICE_QNAME, features);
    }

    public CalculadoraDeParcelaService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CalculadoraDeParcelaService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CalculadoraDeParcela
     */
    @WebEndpoint(name = "CalculadoraDeParcelaPort")
    public CalculadoraDeParcela getCalculadoraDeParcelaPort() {
        return super.getPort(new QName("http://webservices.ae.com.br/", "CalculadoraDeParcelaPort"), CalculadoraDeParcela.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CalculadoraDeParcela
     */
    @WebEndpoint(name = "CalculadoraDeParcelaPort")
    public CalculadoraDeParcela getCalculadoraDeParcelaPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://webservices.ae.com.br/", "CalculadoraDeParcelaPort"), CalculadoraDeParcela.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CALCULADORADEPARCELASERVICE_EXCEPTION!= null) {
            throw CALCULADORADEPARCELASERVICE_EXCEPTION;
        }
        return CALCULADORADEPARCELASERVICE_WSDL_LOCATION;
    }

}
